### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by kmickeletto** [ZuinigeRijder/SolisCloud2PVOutput#10]
Nice script.  Had it running for a few hours this evening and noticed it crashed.

```
20220919 17:54:13: body: {"id":"1306215032078569474","sn":"154AD1199290068"}
20220919 17:55:14: data=20220919,17:53,11100,510,-1,237.9,108.5,360.0
20220919 17:59:17: data=20220919,17:58,11135,430,-1,238.7,107.8,363.4
20220919 18:04:21: data=20220919,18:03,11200,460,-1,238.8,107.2,356.0
20220919 18:09:24: data=20220919,18:08,11237,450,-1,238.7,107.1,356.0
20220919 18:14:28: data=20220919,18:13,11300,510,-1,238.4,106.5,360.1
20220919 18:19:32: data=20220919,18:18,11351,620,-1,237.9,106.9,360.1
20220919 18:24:36: data=20220919,18:23,11392,500,-1,238.5,106.9,367.9
20220919 18:29:40: data=20220919,18:28,11421,350,-1,238.3,106.0,352.1
20220919 18:34:43: data=20220919,18:33,11442,260,-1,238.3,105.3,348.1
20220919 18:39:47: data=20220919,18:38,11455,160,-1,237.8,104.5,347.4
20220919 18:44:52: data=20220919,18:43,11460,60,-1,238.1,103.8,336.1
20220919 18:48:55: data=20220919,18:48,11461,20,-1,238.2,102.6,313.8
20220919 18:53:59: data=20220919,18:53,11462,20,-1,238.0,101.1,309.0
20220919 18:59:02: data=20220919,18:58,11463,20,-1,237.7,100.4,304.5
20220919 19:04:06: data=20220919,19:04,11464,20,-1,237.3,99.7,298.5
20220919 19:09:09: data=20220919,19:09,11465,20,-1,242.2,99.1,294.5
20220919 19:14:13: data=20220919,19:14,11466,20,-1,240.7,98.6,330.8
20220919 19:19:17: data=20220919,19:19,11467,20,-1,240.8,97.9,329.3
20220919 19:24:20: data=20220919,19:24,11500,20,-1,240.4,97.3,289.4
20220919 19:29:24: data=20220919,19:29,11501,20,-1,240.9,97.0,286.6
20220919 19:34:29: data=20220919,19:34,11502,20,-1,241.1,96.4,284.0
20220919 19:39:33: data=20220919,19:39,11503,20,-1,241.2,96.3,281.79999999999995
Traceback (most recent call last):
  File "solis.py", line 223, in <module>
    main_loop()
  File "solis.py", line 200, in main_loop
    hi_res_watthour_today += int(watt/(60/elapsed_minutes))
ZeroDivisionError: division by zero
```

It seems to be right as the data stopped uploading from the inverter to the soliscloud.

**Comment by ZuinigeRijder** [comment]
Apparently the following calculation gives 0 a few lines above:

elapsed_minutes = round(
   (int(timestamp_current) - int(timestamp_previous)) / 60000
)

And this gives a ZeroDivisionError: division by zero
hi_res_watthour_today += int(watt/(60/elapsed_minutes))

Can you also post the other data from that day?
Are in SolisCloud the updates more often than once a minute?

**Comment by kmickeletto** [comment]
They don't appear to be.

https://pvoutput.org/intraday.jsp?id=106839&sid=93493&dt=20220919

**Comment by ZuinigeRijder** [comment]
Ok, latest commit contains the avoidance of this issue:

b0ebb6c5de85419ffc602f616fe5ad731251d705 (HEAD -> main, origin/main, origin/HEAD) avoid ZeroDivisionError and log TIMESTAMPERROR when it occurs, issue #10

See what TIMESTAMPERROR messages will appear over time......

You have to fetch latest version of:
https://github.com/ZuinigeRijder/SolisCloud2PVOutput/blob/main/soliscloud_to_pvoutput.py

**Comment by ZuinigeRijder** [comment]
No feedback, avoiding issue committed a time ago.
