### ISSUE TITLE
SolisCloud API https://www.soliscloud.com:13333/v1/api/userStationList no longer returns station_id

### ISSUE THREAD

**Issue by ZuinigeRijder** [ZuinigeRijder/SolisCloud2PVOutput#4]
SolisCloud API no longer returns the inverter list.

Traceback (most recent call last):
  File "C:\Users\Rick\git\Python\soliscloud_to_pvoutput.py", line 206, in <module>
    main_loop()
  File "C:\Users\Rick\git\Python\soliscloud_to_pvoutput.py", line 147, in main_loop
    inverter_detail_body = get_inverter_list_body()
  File "C:\Users\Rick\git\Python\soliscloud_to_pvoutput.py", line 131, in get_inverter_list_body
    station_info = json.loads(content)['data']['page']['records'][0]
IndexError: list index out of range

If I look what is now returned for my inverter, this is much different than it was before (I checked also with older code, does no longer work). This is now returned for the call https://www.soliscloud.com:13333/v1/api/userStationList
{
  "success": true,
  "code": "0",
  "msg": "success",
  "data": {
    "stationStatusVo": {
      "all": 1,
      "normal": 1,
      "fault": 0,
      "offline": 0,
      "building": 0,
      "mppt": 0
    },
    "page": {
      "records": [],
      "total": 0,
      "size": 10,
      "current": 1,
      "orders": [],
      "optimizeCountSql": true,
      "searchCount": true,
      "pages": 0
    },
    "mpptSwitch": 1
  }
}

**Comment by ZuinigeRijder** [comment]
Today the SolisCloud server was giving back the expected values again, without having done anything myself. So 2 days the scripts were not working due to SolisCloud server problems, apparently they have fixed them.
